# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9798ce035b1343548f9a3f7513f5d5cbc22639350b741b857421e433bff39255914e3df4bc8aa9a3939dd737f05ee7a489471c1927533d63d1616c43281bf111

test:
  secret_key_base: 865008ae54a97d2de3525682dca7a28967e95398f4ca661af2c5c5953a738fcdb2b71f7b7c596678c604316471fd0d642f9951458e9da094485dc9a18b8d2e35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
